#!/usr/bin/env bash

set -eu -o pipefail

help() {
  cat << 'HELP'
Usage: gitlab_hook_merge_requests --logdir DIR --merge-requests JSON_FILE --hooks TSV_FILE
HELP
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=gitlab.bash
source "$script_dir/gitlab.bash"

while test "$#" -gt 0; do
  case "$1" in
    --help           ) help; exit 0 ;;
    --logdir         ) logdir=$2; shift 2 ;;
    --merge-requests ) merge_requests=$2; shift 2 ;;
    --hooks          ) hooks=$2; shift 2 ;;
    --*              ) echo "error: unknown option $1"; exit 1 ;;
    * ) break ;;
  esac
done

: "${logdir?}"
: "${merge_requests?}"
: "${hooks?}"

value_from_ltsv() {
  key="${1?}"
  sed -E "s/(^|.*\t)${key}:([^\t]*).*/\2/"
}

exit_status=0
while read -r line; do
  hook_id=$(echo "$line" | value_from_ltsv "hook_id" )
  filter=$(echo "$line" | value_from_ltsv "filter" )
  cmd=$(echo "$line" | value_from_ltsv "cmd" )
  hook_merge_requests --logdir "$logdir" \
    --hook-id "$hook_id" --filter "$filter" --cmd "$cmd" < "$merge_requests" \
    || exit_status=$?
done < "$hooks"

exit "$exit_status"
