#!/usr/bin/env bash

set -eu

post_message() {
  : "${SLACK_API_TOKEN:?}"
  : "${SLACK_USER_NAME:="Bot"}"
  : "${SLACK_USER_ICON:="https://image.flaticon.com/icons/png/512/57/57369.png"}"
  channel=${1:?}
  text=${2:?}

  body_template=$(cat << 'EOS'
    {
      "as_user": false,
      "username": $username,
      "icon_url": $icon,
      "channel": $channel ,
      "text": $text
    }
EOS
)
  body=$(
    jq -n \
      --arg username "$SLACK_USER_NAME" \
      --arg icon "$SLACK_USER_ICON" \
      --arg channel "$channel" \
      --arg text "$text" \
      "$body_template"
  )
  curl -X POST 'https://slack.com/api/chat.postMessage' \
    -H "Authorization: Bearer $SLACK_API_TOKEN" \
    -H "Content-type: application/json; charset=utf-8" \
    -d "$body"
}

with_message() {
  : "${SLACK_CHANNEL?}"
  : "${SLACK_MESSAGE_ON_SUCCESS?}"
  : "${SLACK_MESSAGE_ON_FAIL?}"

  return_code="0"
  if "$@"; then
    return_code="$?"
    post_message "$SLACK_CHANNEL" "$SLACK_MESSAGE_ON_SUCCESS"
  else
    return_code="$?"
    post_message "$SLACK_CHANNEL" "$SLACK_MESSAGE_ON_FAIL"
  fi
  return "$return_code"
}

email2userid() {
  email="${1?}"
  curl -s -X GET \
    'https://slack.com/api/users.list' \
    -H "Authorization: Bearer $SLACK_API_TOKEN" \
    | jq -r ".members | map(select(.profile.email == \"$email\")) | .[0].id"
}


"$@"
