#!/usr/bin/env bash

set -eu -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=gitlab.bash
source "$script_dir/gitlab.bash"

require_envs
: "${GITLAB_MR_IID?}"
: "${GITLAB_MR_COMMENT_ON_START?}"
: "${GITLAB_MR_COMMENT_ON_CANCEL?}"
: "${GITLAB_MR_COMMENT_ON_SUCCESS?}"
: "${GITLAB_MR_COMMENT_ON_FAIL?}"

on_exit() {
  local exit_status="$?"
  if test "$exit_status" -eq 0; then
    comment_on_merge_request "$GITLAB_MR_IID" "$GITLAB_MR_COMMENT_ON_SUCCESS"
  else
    comment_on_merge_request "$GITLAB_MR_IID" "$GITLAB_MR_COMMENT_ON_FAIL"
  fi
  return "$exit_status"
}

on_cancel() {
  comment_on_merge_request "$GITLAB_MR_IID" "$GITLAB_MR_COMMENT_ON_CANCEL"
  trap -- EXIT
  trap -- TERM
  kill -s TERM $$
}

trap 'on_exit' EXIT
trap 'on_cancel' HUP INT QUIT TERM

comment_on_merge_request "$GITLAB_MR_IID" "$GITLAB_MR_COMMENT_ON_START"

"$@" &
wait "$(jobs -p)"
