#!/usr/bin/env bash

set -eu

this_dir="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=slack.bash
source "$this_dir/slack.bash"

: "${SLACK_API_TOKEN?}"
: "${SLACK_CHANNEL?}"
: "${SLACK_MESSAGE_ON_START:=""}"
: "${SLACK_MESSAGE_ON_CANCEL:=""}"
: "${SLACK_MESSAGE_ON_SUCCESS:=""}"
: "${SLACK_MESSAGE_ON_FAIL:=""}"
: "${SLACK_USER_NAME:="Bot"}"
: "${SLACK_USER_ICON:="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/GNOME_Builder_Icon_%28hicolor%29.svg/240px-GNOME_Builder_Icon_%28hicolor%29.svg.png"}"


post_message_if_not_empty() {
  channel="${1?}"
  message="${2?}"
  if test -n "$message"; then
    post_message "$channel" "$message"
  fi
}

on_exit() {
  exit_code="$?"
  if test "$exit_code" = "0"; then
    post_message_if_not_empty "$SLACK_CHANNEL" "$SLACK_MESSAGE_ON_SUCCESS"
  else
    post_message_if_not_empty "$SLACK_CHANNEL" "$SLACK_MESSAGE_ON_FAIL"
  fi
  return "$exit_code"
}

on_cancel() {
  post_message_if_not_empty "$SLACK_CHANNEL" "$SLACK_MESSAGE_ON_CANCEL"
  trap -- EXIT
  trap -- TERM
  kill -s TERM $$
}

trap 'on_exit' EXIT
trap 'on_cancel' HUP INT QUIT TERM

post_message_if_not_empty "$SLACK_CHANNEL" "$SLACK_MESSAGE_ON_START"

"$@" &
wait "$(jobs -p)"
