name: verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test with_dockerfile
      run: bash ./with_dockerfile.test.bash 2> test.log || cat test.log

    - name: lint test
      run: ./with_dockerfile --verbose make lint test
