name: verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test with_dockerfile
      run: env TERM=xterm ./run_tests.bash ./with_dockerfile.test.bash

    - name: lint test
      run: ./with_dockerfile --verbose env TERM=xterm make lint test
